In [1]:
# Load the pandas library. It contains the functions related with Table. Create Alias name as pd for referring the library
import pandas as pd

In [3]:
#Step1: Data Collection
# Use the pandas function read_csv to read the CSV (Comma Separated Values file) from the root folder. Assign the output to the variable df.
df = pd.read_csv("Salary_Data.csv")

In [5]:
# Print the df to check all the input data exist in the variable or not.
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [7]:
#Step2: Since there is no issue with data, data preprocessing hasn't done.
#Step3: Split the Input & Output data
#By using the column name get the input & output data and assign to the separate variables. Since it is Linear regression it has 1 input and 1 output column
#Input data. 
independent = df[["YearsExperience"]]
#Output data.
dependent = df[["Salary"]]

In [11]:
#print the input variable to check the values are correct.
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [13]:
#print the output variable to check the values are correct.
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [15]:
#Step4: Split the Train and Test data
#By using the sklearn packages, load the train_test_split function alone.
from sklearn.model_selection import train_test_split

In [23]:
#passing the input and output variables to this function and get the split data (Train - X, Y and Test - X, Y)
X_train, X_test, y_train, y_test = train_test_split(independent, dependent)

In [33]:
#print the X Train value
X_train

    YearsExperience
18              5.9
13              4.1
8               3.2
0               1.1
20              6.8
28             10.3
23              8.2
14              4.5
4               2.2
17              5.3
1               1.3
12              4.0
19              6.0
24              8.7
11              4.0
21              7.1
16              5.1
10              3.9
2               1.5
15              4.9
9               3.7
26              9.5

In [35]:
#print the X Test value
X_test

    YearsExperience
3               2.0
7               3.2
29             10.5
22              7.9
6               3.0
27              9.6
5               2.9
25              9.0

In [37]:
#print the Y Train value
y_train

      Salary
18   81363.0
13   57081.0
8    64445.0
0    39343.0
20   91738.0
28  122391.0
23  113812.0
14   61111.0
4    39891.0
17   83088.0
1    46205.0
12   56957.0
19   93940.0
24  109431.0
11   55794.0
21   98273.0
16   66029.0
10   63218.0
2    37731.0
15   67938.0
9    57189.0
26  116969.0

In [39]:
#print the Y Test value
y_test

      Salary
3    43525.0
7    54445.0
29  121872.0
22  101302.0
6    60150.0
27  112635.0
5    56642.0
25  105582.0

In [41]:
#Step5: Create Model
#Load the LinearRegression class from the sklearn.linear_model package
from sklearn.linear_model import LinearRegression

In [43]:
#Create object to the class
regressor = LinearRegression()

In [47]:
#Train the model using the X Train and Y Train data
#Output model will be generated.
regressor.fit(X_train,y_train)

LinearRegression()

In [53]:
#Get the Predicted values based on the Test data 
y_pred = regressor.predict(X_test)
y_pred

array([[ 43457.79377194],
       [ 55366.24316898],
       [127809.3103343 ],
       [102007.66997405],
       [ 53381.50160281],
       [118877.97328652],
       [ 52389.13081972],
       [112923.748588  ]])

In [55]:
#Step6: Evaluate the metrics
#import the r2_score function from the sklearn.metrics package
from sklearn.metrics import r2_score

In [59]:
#calculate the r2 metrics based on Y test and Y pred values.
#assign the metrics result to the variable
# metric value should between 0 and 1. model will perform good if the metric value is closure to 1.
result_score = r2_score(y_test,y_pred)
result_score

0.9716329718054353

In [63]:
#Calulate the weight
weight = regressor.coef_
weight

array([[9923.70783087]])

In [65]:
#Calculate the bias
bias = regressor.intercept_
bias

array([23610.37811021])

In [67]:
# Linear regression equation is y=mx+c, m is slope/weight and c is origin/intercept
#Step 7: Save the model
#Using Picle library save the model to the local
import pickle
#Create a file name and assign to the variable for save the model
filename = "linear_model.sav"

In [69]:
#using the dump function save the created model to the root folder with the file name defined earlier using write binary.
#After execution we can see the file created in the root folder
pickle.dump(regressor, open(filename,"wb"))

In [71]:
#The created model used to predict any salary based on the input YearsOfExperiance
#Step 8: Load the model
#Load the model by locating the saved file using read binary and assign to the variable for prediction
result_model = pickle.load(open(filename,"rb"))

In [81]:
#Step 9: Predict using model
#Step 10: Call to Action
final_result = result_model.predict([[0]])
final_result

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[23610.37811021]])